# Generated by Django 3.2 on 2021-06-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_picture',
            field=models.ImageField(default='background_pictures/default_background.jpg', upload_to='background_pictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile.jpg', upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
