# Generated by Django 3.2 on 2021-06-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morfeusz_app', '0003_alter_movie_options'),
        ('users', '0002_auto_20210601_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='movies_like_dont_watch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movies_like_watch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movies_watch',
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_dont_want_to_watch',
            field=models.ManyToManyField(related_name='linked_profiles_dont_want_to_watch', to='morfeusz_app.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_like',
            field=models.ManyToManyField(related_name='linked_profiles_like', to='morfeusz_app.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_want_to_watch',
            field=models.ManyToManyField(related_name='linked_profiles_want_to_watch', to='morfeusz_app.Movie'),
        ),
    ]
