# Generated by Django 3.2 on 2021-06-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morfeusz_app', '0004_alter_movie_options'),
        ('users', '0003_auto_20210603_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='movies_dont_want_to_watch',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movies_like',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movies_want_to_watch',
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_like_dont_watch',
            field=models.ManyToManyField(related_name='linked_profiles_like_dont_watch', to='morfeusz_app.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_like_watch',
            field=models.ManyToManyField(related_name='linked_profiles_like_watch', to='morfeusz_app.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='movies_watch',
            field=models.ManyToManyField(related_name='linked_profiles_watch', to='morfeusz_app.Movie'),
        ),
    ]
