# Generated by Django 3.2.1 on 2021-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(default='0000000', max_length=7)),
                ('title', models.CharField(default='', max_length=255)),
                ('genre', models.CharField(default='', max_length=255)),
                ('cover_url', models.CharField(default='', max_length=255)),
            ],
            options={
                'ordering': ['imdb_id'],
            },
        ),
    ]
