# Generated by Django 3.2 on 2021-06-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfeusz_app', '0002_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
    ]
