# Generated by Django 3.2 on 2021-06-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morfeusz_app', '0003_alter_movie_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['imdb_id']},
        ),
    ]
