name: Django Unittest

on: push

jobs:
  test:
    name: Run Unittest
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install
      run: |
        pip install -r .github/workflows/requirements.txt
        
    - name: Run migrations
      run: python manage.py migrate
    - name: Test
      run: python manage.py test
