name: ML Unittest

on: push

jobs:
  test:
    name: Run Unittest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        pip install numpy==1.19.5
    - name: Test
      working-directory: ./morfeusz_app/TensorFlow
      run: python ML_unittest.py
