name: Morfeusz_app Unittest

on: push

jobs:
  test:
    name: Run Unittest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install
      run: |
        pip install django
        export DJANGO_SETTINGS_MODULE = morfeusz.settings
    - name: Test
      working-directory: ./morfeusz_app
      run: python tests.py
