name: Automated Unittest

on: push

jobs:
  test:
    name: Run Unittest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        pip install pandas
        pip install opencv-python
        pip install tqdm
    - name: Test
      working-directory: ./TensorFlow
      run: python automated_unittest.py
