name: Automated Unittest

on: push

jobs:
  test:
    name: Run Unittest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: |
        pip install pandas
        pip install opencv-python
        pip install tqdm
    - name: Test
      run: python TensorFlow/automated_unittest.py
