name: Automated Unittest

on: push

jobs:
  test:
    name: Run Unittest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        pip install pandas
        pip install opencv-python
    - name: Test
      run: python TensorFlow/automated_unittest.py
